#!/bin/zsh
# Skill Scout — weekly scan of Claude Code sessions to surface repeatable processes.
# Runs every Monday at 9am. Uses a zsh login shell so PATH and env vars are available.

set -euo pipefail

CLAUDE="/Users/abhishek.shah/.local/bin/claude"
BRAIN="$HOME/pm/brain"
LOG="$BRAIN/logs/skill-scout.log"
SCRATCH="$BRAIN/knowledge/scratch"

mkdir -p "$BRAIN/logs" "$SCRATCH"

WEEK=$(date +%G-W%V)
TODAY=$(date +%Y-%m-%d)
OUTFILE="$SCRATCH/skill-suggestions-$WEEK.md"

echo "[$(date '+%Y-%m-%d %H:%M')] Skill Scout starting for week $WEEK..." >> "$LOG"

# Step 1: Python script scans transcripts and writes the analysis prompt
python3 "$BRAIN/scripts/skill-scout.py" --days 7 >> "$LOG" 2>&1

PROMPT_FILE="$SCRATCH/_skill_scout_prompt.txt"

if [[ ! -f "$PROMPT_FILE" ]]; then
    echo "[$(date '+%Y-%m-%d %H:%M')] No prompt file generated — no sessions found. Exiting." >> "$LOG"
    exit 0
fi

SESSION_COUNT=$(grep -c "^Session " "$PROMPT_FILE" 2>/dev/null || echo "0")
echo "[$(date '+%Y-%m-%d %H:%M')] Analyzing $SESSION_COUNT sessions with Claude..." >> "$LOG"

# Step 2: Claude analyzes the prompt and writes the report
"$CLAUDE" \
  --allowedTools "Write" \
  -p "$(cat <<PROMPT
Read the following session analysis prompt carefully. Identify repeatable processes that should become skills.
Then write a complete skill suggestions report to: $OUTFILE

Use this frontmatter at the top:
---
title: Skill Suggestions — $WEEK
category: scratch
tags: [skill-scout, automation, weekly]
created: $TODAY
updated: $TODAY
---

Then a heading: # Skill Suggestions — $WEEK
Subheading: *Generated by Skill Scout on $TODAY. Run \`/skill-scout\` to draft any of these into a real skill.*

Then your analysis.

---
$(cat "$PROMPT_FILE")
PROMPT
)" >> "$LOG" 2>&1

# Step 3: Clean up temp prompt file
rm -f "$PROMPT_FILE"

if [[ -f "$OUTFILE" ]]; then
    echo "[$(date '+%Y-%m-%d %H:%M')] Report saved: $OUTFILE" >> "$LOG"
else
    echo "[$(date '+%Y-%m-%d %H:%M')] WARNING: Report file not created." >> "$LOG"
fi

echo "[$(date '+%Y-%m-%d %H:%M')] Skill Scout complete." >> "$LOG"
